services:
  - type: web
    name: uber-eats-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps         
    startCommand: uvicorn scraper.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 